name: Build and deploy Node.js app to Azure Web App - Slidy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Adjust this to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Archive artifacts
        run: |
          zip -r release.zip ./*
          mv release.zip $GITHUB_WORKSPACE
        working-directory: ./public

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: $GITHUB_WORKSPACE/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip ${{ runner.workspace }}/release.zip -d ${{ runner.workspace }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          package: ${{ runner.workspace }}
